project_id = "rdybckvifirurunqlqfr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
image = "supabase/gotrue:v2.158.1"
port = 9999
external_url = "http://localhost:3000"

[db]
enabled = true
port = 54322
image = "supabase/postgres:15.1.1.78"
password = "postgres"
pooler_enabled = false
pooler_port = 54329

[functions.ai-chat]
verify_jwt = true

[functions.ai-insights]
verify_jwt = true

[functions.health-analysis]
verify_jwt = true

[functions.generate-image]
verify_jwt = true