// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdybckvifirurunqlqfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkeWJja3ZpZmlydXJ1bnFscWZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMDcxMTYsImV4cCI6MjA3MTU4MzExNn0.9-AWXAIAQSmpr8c7WaPivMxrc6AALuN7basFHMk7Ygw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});